# Generated by Django 4.2.7 on 2025-01-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone_number', models.CharField(max_length=15)),
                ('subject', models.CharField(max_length=150, verbose_name='موضوع')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('is_read_by_admin', models.BooleanField(blank=True, default=False, null=True, verbose_name='خوانده شده / نشده توسط ادمین')),
            ],
            options={
                'verbose_name': 'ارتباط با ما',
                'verbose_name_plural': 'تماس با ما',
            },
        ),
    ]
