# Generated by Django 4.2.7 on 2025-01-26 14:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import home_module.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name and surname')),
                ('job', models.CharField(max_length=500, verbose_name='Job title')),
                ('personal_background_image', models.ImageField(upload_to='Background-Personal/', verbose_name='Personal background image')),
                ('main_profile', models.ImageField(upload_to='Main-Profile/', verbose_name='Profile picture')),
                ('about_me', models.TextField(verbose_name='About')),
                ('years_experience', models.IntegerField(verbose_name='Years experience')),
                ('curriculum_vitae', models.FileField(upload_to='pdfs/', validators=[home_module.validators.validate_pdf], verbose_name='Curriculum vitae')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('services_main_description', models.TextField(verbose_name='Services main description')),
                ('author', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('percentage', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Percentage')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_module.personalinformation')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='PersonalServices/logo/', verbose_name='Logo')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Services description')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_module.personalinformation')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalLastestWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('image', models.ImageField(upload_to='Lastes-work/', verbose_name='Image')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_module.personalinformation')),
            ],
        ),
        migrations.CreateModel(
            name='OurCustomerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(upload_to='PersonalServices/Opinionprofile/', verbose_name='Profile')),
                ('name', models.CharField(max_length=150, verbose_name='Name and surname')),
                ('job', models.CharField(max_length=500, verbose_name='Job title')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='home_module.personalinformation')),
            ],
        ),
    ]
