# Generated by Django 4.2.7 on 2025-01-16 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wearedeconsult',
            old_name='text',
            new_name='title',
        ),
    ]
