# Generated by Django 4.2.7 on 2025-01-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0002_rename_text_wearedeconsult_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurServiceQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان پرسش')),
                ('question', models.CharField(max_length=250, verbose_name='سوالات')),
                ('response', models.CharField(max_length=400, verbose_name='پاسخ سوالات')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان سرویس')),
            ],
        ),
        migrations.CreateModel(
            name='OurService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='Ourservice/logo')),
                ('title', models.TextField(max_length=150, verbose_name='عنوان')),
                ('short_desc', models.TextField(max_length=150, verbose_name='متن توضیحات کوتاه')),
                ('main_desc', models.TextField(max_length=350, verbose_name='متن توضیحات')),
                ('image', models.ImageField(upload_to='Ourservice/image', verbose_name='تصویر محصول')),
                ('blue_part_desc', models.TextField(max_length=350, verbose_name='توضیحات قسمت آبی')),
                ('sentences', models.CharField(max_length=150, verbose_name='جملات')),
                ('questions', models.ManyToManyField(to='home_module.ourservicequestion', verbose_name='سوالات')),
                ('service', models.ManyToManyField(to='home_module.services', verbose_name='سرویس ها')),
            ],
        ),
    ]
