# Generated by Django 4.2.7 on 2025-01-16 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0003_ourservicequestion_services_ourservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=150, verbose_name='متن جمله')),
            ],
        ),
        migrations.RemoveField(
            model_name='ourservice',
            name='sentences',
        ),
        migrations.AddField(
            model_name='ourservice',
            name='sentences',
            field=models.ManyToManyField(to='home_module.sentences', verbose_name='جملات'),
        ),
    ]
