# Generated by Django 4.2.7 on 2025-01-17 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0005_rename_logo_ourservice_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ourservice',
            options={'verbose_name': 'سرویس ما', 'verbose_name_plural': 'سرویس های ما'},
        ),
        migrations.AlterModelOptions(
            name='ourservicequestion',
            options={'verbose_name': 'سوال', 'verbose_name_plural': 'سوالات'},
        ),
        migrations.AlterModelOptions(
            name='sentences',
            options={'verbose_name': 'جمله', 'verbose_name_plural': 'جملات'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'سرویس'},
        ),
        migrations.AlterModelOptions(
            name='wearedeconsult',
            options={'verbose_name': 'عدم مشاوره', 'verbose_name_plural': 'عدم مشورت'},
        ),
        migrations.AlterModelOptions(
            name='wearedeconsultoptions',
            options={'verbose_name': 'نظر', 'verbose_name_plural': 'نظرات'},
        ),
        migrations.AddField(
            model_name='ourservice',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=200, unique=True, verbose_name='عنوان در url'),
        ),
        migrations.AlterField(
            model_name='wearedeconsult',
            name='title',
            field=models.TextField(max_length=150, verbose_name='متن  توضیحات'),
        ),
    ]
